[project]
name = "listaccounts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "paho-mqtt==2.1.0",
    "pip==24.0",
    "python-dotenv==1.1.0",
    "slack-sdk==3.25.0",
    "boto3",
    "botocore",
    "toml"
]
